/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import datos.AlmacenamientoViviendas;
import datos.AlmacenamientoInquilinos;
import datos.AlmacenamientoAlquileres;
import logica.Alquiler;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;

/**
 * Ventana principal de Gestion de Contratos de Alquiler
 *
 * @author cahb294
 * @author BrianOrozco
 * @author MariaGallo
 */
public class JDlgMainAlquiler extends javax.swing.JDialog {

    /**
     * Referencia al almacenamiento de Viviendas
     */
    public AlmacenamientoViviendas listaViviendas;
    
    /**
     * Referencia al almacenamiento de Inquilinos
     */
    public AlmacenamientoInquilinos listaInquilinos;
    
    /**
     * Referencia al almacenamiento de Contratos de Alquiler
     */
    public AlmacenamientoAlquileres listaAlquileres;

    /**
     * Modelo de tabla para mostrar los datos
     */
    private DefaultTableModel tblModel;
    
    /**
     * Formato de fecha: Dia/Mes/Año → dd/MM/yyyy 
     */
    private final DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form JDlgAlquiler
     */
    public JDlgMainAlquiler(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Constructor de la Ventana Principal
     * @param parent Ventana padre
     * @param modal Si la ventana bloquea a la anterior al abrirse
     * @param listaViviendas Objeto con la lista de viviendas registradas
     * @param listaInquilinos Objeto con la lista de inquilinos registrados
     * @param listaAlquileres Objeto con la lista de contratos de alquiler
     */
    public JDlgMainAlquiler(java.awt.Frame parent, boolean modal,
            AlmacenamientoViviendas listaViviendas,
            AlmacenamientoInquilinos listaInquilinos,
            AlmacenamientoAlquileres listaAlquileres) {

        super(parent, modal);
        initComponents();

        this.listaViviendas = listaViviendas;
        this.listaInquilinos = listaInquilinos;
        this.listaAlquileres = listaAlquileres;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAlquileres = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTituloAlquileres = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblIlustrativo = new javax.swing.JLabel();
        lblTituloRegistroAlquileres = new javax.swing.JLabel();
        txtBarraBuscar = new javax.swing.JTextField();
        PnlOpcionesUsuario = new javax.swing.JPanel();
        BttnNuevo = new javax.swing.JButton();
        BttnEditar = new javax.swing.JButton();
        BttnEliminar = new javax.swing.JButton();
        BttnRegresar = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblAlquileres = new javax.swing.JTable();
        lblTotalRegistro = new javax.swing.JLabel();
        txtCantReg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Alquileres");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlAlquileres.setBackground(new java.awt.Color(0, 153, 153));
        pnlAlquileres.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        pnlAlquileres.setForeground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoGuanaRent1.png"))); // NOI18N
        lblLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTituloAlquileres.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloAlquileres.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        lblTituloAlquileres.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloAlquileres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloAlquileres.setText("- Alquileres - ");

        lblIlustrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alquileres8.png"))); // NOI18N

        javax.swing.GroupLayout pnlAlquileresLayout = new javax.swing.GroupLayout(pnlAlquileres);
        pnlAlquileres.setLayout(pnlAlquileresLayout);
        pnlAlquileresLayout.setHorizontalGroup(
            pnlAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlquileresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloAlquileres)
                .addGap(34, 34, 34))
            .addGroup(pnlAlquileresLayout.createSequentialGroup()
                .addGroup(pnlAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlquileresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)))
                    .addGroup(pnlAlquileresLayout.createSequentialGroup()
                        .addGroup(pnlAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAlquileresLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblLogo))
                            .addGroup(pnlAlquileresLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lblIlustrativo)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAlquileresLayout.setVerticalGroup(
            pnlAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlquileresLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblIlustrativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloAlquileres)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTituloRegistroAlquileres.setBackground(new java.awt.Color(153, 153, 0));
        lblTituloRegistroAlquileres.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblTituloRegistroAlquileres.setForeground(new java.awt.Color(153, 153, 0));
        lblTituloRegistroAlquileres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRegistroAlquileres.setText("  Registro de Alquileres ");

        txtBarraBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarraBuscarActionPerformed(evt);
            }
        });

        PnlOpcionesUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        BttnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new.png"))); // NOI18N
        BttnNuevo.setText("Nuevo");
        BttnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnNuevoActionPerformed(evt);
            }
        });

        BttnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        BttnEditar.setText("Editar");
        BttnEditar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BttnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnEditarActionPerformed(evt);
            }
        });

        BttnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        BttnEliminar.setText("Eliminar");
        BttnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnEliminarActionPerformed(evt);
            }
        });

        BttnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        BttnRegresar.setText("Regresar");
        BttnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlOpcionesUsuarioLayout = new javax.swing.GroupLayout(PnlOpcionesUsuario);
        PnlOpcionesUsuario.setLayout(PnlOpcionesUsuarioLayout);
        PnlOpcionesUsuarioLayout.setHorizontalGroup(
            PnlOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlOpcionesUsuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BttnNuevo)
                .addGap(18, 18, 18)
                .addComponent(BttnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BttnEditar)
                .addGap(18, 18, 18)
                .addComponent(BttnRegresar)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PnlOpcionesUsuarioLayout.setVerticalGroup(
            PnlOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlOpcionesUsuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PnlOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BttnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BttnEditar)
                    .addComponent(BttnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BttnRegresar))
                .addGap(15, 15, 15))
        );

        lblBuscar.setBackground(new java.awt.Color(153, 153, 0));
        lblBuscar.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(0, 102, 102));
        lblBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscar.setText("Buscar:");

        TblAlquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TblAlquileres);

        lblTotalRegistro.setBackground(new java.awt.Color(153, 153, 0));
        lblTotalRegistro.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        lblTotalRegistro.setForeground(new java.awt.Color(0, 102, 102));
        lblTotalRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalRegistro.setText("Total Registrados:");

        txtCantReg.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PnlOpcionesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lblBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(txtBarraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTituloRegistroAlquileres)
                                .addGap(97, 97, 97)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantReg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAlquileres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblTituloRegistroAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBarraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar))
                .addGap(18, 18, 18)
                .addComponent(PnlOpcionesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalRegistro))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBarraBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarraBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBarraBuscar.getText().trim().toLowerCase();

        if (texto.isEmpty()) {
            muestraTabla(); 
            return;
        }
    }//GEN-LAST:event_txtBarraBuscarActionPerformed

    /**
     * Boton NUEVO se Abre formulario para registrar contrato nuevo
     * @param evt Evento de clic del boton
     */
    private void BttnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnNuevoActionPerformed
        // TODO add your handling code here:
        JDlgNewAlquiler formulario = new JDlgNewAlquiler(null, true, listaViviendas, listaInquilinos, listaAlquileres);
        formulario.setVisible(true);
        muestraTabla();

    }//GEN-LAST:event_BttnNuevoActionPerformed

    /**
     * Boton ELIMINAR, Borra contrato seleccionado.
     * @param evt Evento de clic del boton
     */
    private void BttnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnEliminarActionPerformed
        // TODO add your handling code here:
        if (TblAlquileres.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(this,"Seleccione 1 SOLO contrato para eliminar","Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = TblAlquileres.getSelectedRow();
        Alquiler alq = listaAlquileres.getListaAlquileres().get(fila);

        int resp = JOptionPane.showConfirmDialog(this,"¿Eliminar Contrato Nº " + alq.getNumAlquiler() + "?\n"
                + "Vivienda: " + alq.getIdVivienda() + "\n"
                + "Al eliminar, la vivienda quedara DISPONIBLE.",
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (resp == JOptionPane.YES_OPTION) {
            if (listaAlquileres.eliminarAlquiler(alq.getIdVivienda())) {
                JOptionPane.showMessageDialog(this,
                        "Contrato eliminado.\nVivienda ahora está DISPONIBLE.",
                        "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
                muestraTabla();
            }
        }
    }//GEN-LAST:event_BttnEliminarActionPerformed

    /**
     * Boton EDITAR, Abre formulario con datos del contrato seleccionado
     * Validación: Debe seleccionarse UNA sola fila de la tabla
     * @param evt Evento de clic del botón
     */
    private void BttnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnEditarActionPerformed
        // TODO add your handling code here:
        if (TblAlquileres.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(this,"Seleccione 1 SOLO contrato en la tabla","Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = TblAlquileres.getSelectedRow();
        Alquiler alq = listaAlquileres.getListaAlquileres().get(fila);
        JDlgNewAlquiler win = new JDlgNewAlquiler(null, true, listaViviendas, listaInquilinos, listaAlquileres, alq, fila);
        win.setTitle("Editar Contrato Nº " + alq.getNumAlquiler());
        win.setVisible(true);
        muestraTabla();
    }//GEN-LAST:event_BttnEditarActionPerformed

    /**
     * Boton REGRESAR, Cierra esta ventana y vuelve al menú principal.
     * @param evt Evento de clic del boton
     */
    private void BttnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BttnRegresarActionPerformed

    /**
     * Evento que se ejecuta al abrir o activar la ventana.
     * @param evt Evento de activacion de ventana
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        muestraTabla();
    }//GEN-LAST:event_formWindowActivated

    /**
     * Construye la tabla y llena filas con todos los contratos registrados
     */
    private void muestraTabla() {
        String[] titulos = {"Nº Contrato", "Vivienda", "Fecha Contrato", "Meses", "Inquilino", "Precio Mensual", "Estado"};
        tblModel = new DefaultTableModel(null, titulos);

        for (Alquiler alq : listaAlquileres.getListaAlquileres()) {
            Object[] fila = {
                alq.getNumAlquiler(),
                alq.getIdVivienda(),
                alq.getFechContrato().format(formato),
                alq.getCantMeses(),
                alq.getCedInquilino(),
                "₡" + String.format("%,.2f", alq.getPrecioAlquiler()),
                alq.getEstado()
            };
            tblModel.addRow(fila);
        }
        TblAlquileres.setModel(tblModel);
        txtCantReg.setText(String.valueOf(tblModel.getRowCount()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMainAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMainAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMainAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMainAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMainAlquiler dialog = new JDlgMainAlquiler(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnEditar;
    private javax.swing.JButton BttnEliminar;
    private javax.swing.JButton BttnNuevo;
    private javax.swing.JButton BttnRegresar;
    private javax.swing.JPanel PnlOpcionesUsuario;
    private javax.swing.JTable TblAlquileres;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblIlustrativo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloAlquileres;
    private javax.swing.JLabel lblTituloRegistroAlquileres;
    private javax.swing.JLabel lblTotalRegistro;
    private javax.swing.JPanel pnlAlquileres;
    private javax.swing.JTextField txtBarraBuscar;
    private javax.swing.JTextField txtCantReg;
    // End of variables declaration//GEN-END:variables
}
