/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import datos.AlmacenamientoViviendas;
import datos.AlmacenamientoPropietarios;
import javax.swing.JOptionPane;
import logica.Vivienda;
import logica.Propietario;

/**
 * Formulario para AGREGAR o EDITAR un registro de Vivienda.
 * @author cahb294
 * @author BrianOrozco
 * @author MariaGallo
 */
public class JDlgNewVivienda extends javax.swing.JDialog {

    public AlmacenamientoViviendas listaViviendas;
    protected AlmacenamientoPropietarios listaPropietarios;
    protected Vivienda viviendaEditar;   
    protected int pos;                 

    /**
     * Creates new form JDlgVivienda
     */
    public JDlgNewVivienda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Constructor -- AGREGAR NUEVA VIVIENDA
     * @param parent Ventana padre
     * @param modal Indica si es ventana modal
     * @param listaViviendas Almacenamiento compartido de viviendas
     */
    public JDlgNewVivienda(java.awt.Frame parent, boolean modal,
            AlmacenamientoViviendas listaViviendas, AlmacenamientoPropietarios listaPropietarios) {
        super(parent, modal);
        initComponents();
        this.listaViviendas = listaViviendas;
        this.listaPropietarios = listaPropietarios;
        cargarComboPropietarios();
        setTitle("Agregar una Nueva Vivienda");
    }

    /**
     * Constructor — EDITAR VIVIENDA 
     * @param parent Ventana padre
     * @param modal Indica si es ventana modal
     * @param listaViviendas Almacenamiento compartido
     * @param listaPropietarios
     * @param viviendaEditar Objeto con los datos originales
     * @param pos Índice en la lista o tabla
     */
    public JDlgNewVivienda(java.awt.Frame parent, boolean modal,
            AlmacenamientoViviendas listaViviendas, AlmacenamientoPropietarios listaPropietarios,Vivienda viviendaEditar, int pos) {
        super(parent, modal);
        initComponents();
        this.listaViviendas = listaViviendas;
        this.listaPropietarios = listaPropietarios; 
        this.viviendaEditar = viviendaEditar;
        this.pos = pos;
        cargarComboPropietarios(); 
        setTitle("Editar Vivienda");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlInformacionViviendas = new javax.swing.JPanel();
        lblIdVivienda = new javax.swing.JLabel();
        lblM2Construccion = new javax.swing.JLabel();
        lblCochera = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTipoConstruccion = new javax.swing.JLabel();
        lblPropietario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtADireccion = new javax.swing.JTextArea();
        CmbBxTipContru = new javax.swing.JComboBox<>();
        lblIlustrativo = new javax.swing.JLabel();
        lblTituloInfromacionVivienda = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtADescripcion = new javax.swing.JTextArea();
        lblCarretera = new javax.swing.JLabel();
        CmbBxTipoCarretera = new javax.swing.JComboBox<>();
        RdBttnSi = new javax.swing.JRadioButton();
        RdBttnNo = new javax.swing.JRadioButton();
        CmboBxEstadoViv = new javax.swing.JComboBox<>();
        CmbBxPropietarios = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        lblCantHabt = new javax.swing.JLabel();
        lblBanios = new javax.swing.JLabel();
        lblLote = new javax.swing.JLabel();
        txtIdVivienda = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblDeposito = new javax.swing.JLabel();
        txtMtsLote = new javax.swing.JTextField();
        txtM2Contruc = new javax.swing.JTextField();
        TxtcantBanios = new javax.swing.JTextField();
        txtCantH = new javax.swing.JTextField();
        txtPrecioBase = new javax.swing.JTextField();
        txtDeposito = new javax.swing.JTextField();
        pnlViviendas = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTituloViviendas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GuanaRent/Viviendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlInformacionViviendas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIdVivienda.setText("ID Vivienda:");

        lblM2Construccion.setText("M² construcción:");

        lblCochera.setText("Cochera: ");

        lblDireccion.setText("Dirección:");

        lblTipoConstruccion.setText("Tipo Construcción:");

        lblPropietario.setText("Propietario:");

        TxtADireccion.setColumns(20);
        TxtADireccion.setRows(5);
        jScrollPane1.setViewportView(TxtADireccion);

        CmbBxTipContru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "Block", "Baldosa", "Super Block", "Madera", "Mixta" }));

        lblIlustrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vivienda8.png"))); // NOI18N

        lblTituloInfromacionVivienda.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        lblTituloInfromacionVivienda.setForeground(new java.awt.Color(0, 153, 153));
        lblTituloInfromacionVivienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloInfromacionVivienda.setText("Información Vivienda");

        lblDescripcion.setText("Descripción:");

        TxtADescripcion.setColumns(20);
        TxtADescripcion.setRows(5);
        jScrollPane2.setViewportView(TxtADescripcion);

        lblCarretera.setText("Carretera:");

        CmbBxTipoCarretera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "Lastre", "Pavimentada", "Adoquinada" }));

        buttonGroup1.add(RdBttnSi);
        RdBttnSi.setText("Sí");

        buttonGroup1.add(RdBttnNo);
        RdBttnNo.setText("No");

        CmboBxEstadoViv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "Disponible", "Alquilada", "Inactiva" }));

        lblEstado.setText("Estado:");

        lblCantHabt.setText("Cant Habitaciones");

        lblBanios.setText("Baños:");

        lblLote.setText("Lote:");

        lblPrecio.setText("Precio:");

        lblDeposito.setText("Depósito:");

        javax.swing.GroupLayout pnlInformacionViviendasLayout = new javax.swing.GroupLayout(pnlInformacionViviendas);
        pnlInformacionViviendas.setLayout(pnlInformacionViviendasLayout);
        pnlInformacionViviendasLayout.setHorizontalGroup(
            pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                        .addComponent(lblIlustrativo)
                        .addGap(173, 173, 173)
                        .addComponent(lblTituloInfromacionVivienda)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                        .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoConstruccion)
                            .addComponent(lblPropietario)
                            .addComponent(lblPrecio))
                        .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(CmbBxTipContru, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionViviendasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CmbBxPropietarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmboBxEstadoViv, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                        .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblIdVivienda)
                                .addComponent(lblDescripcion))
                            .addComponent(lblDireccion))
                        .addGap(18, 18, 18)
                        .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                                .addComponent(txtIdVivienda)
                                .addGap(18, 18, 18)
                                .addComponent(lblLote)
                                .addGap(18, 18, 18)
                                .addComponent(txtMtsLote, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                        .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblM2Construccion)
                                    .addComponent(lblBanios))
                                .addGap(24, 24, 24)
                                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtM2Contruc, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(TxtcantBanios))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCantHabt)
                                    .addComponent(lblCochera)))
                            .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstado)
                                    .addComponent(lblCarretera)
                                    .addComponent(lblDeposito))
                                .addGap(47, 47, 47)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantH)
                            .addGroup(pnlInformacionViviendasLayout.createSequentialGroup()
                                .addComponent(RdBttnSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RdBttnNo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(CmbBxTipoCarretera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(68, 68, 68))
        );
        pnlInformacionViviendasLayout.setVerticalGroup(
            pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionViviendasLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIlustrativo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloInfromacionVivienda, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdVivienda)
                    .addComponent(lblLote)
                    .addComponent(txtIdVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMtsLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCantHabt)
                        .addComponent(txtCantH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblM2Construccion)
                        .addComponent(txtM2Contruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBanios)
                        .addComponent(lblCochera)
                        .addComponent(RdBttnSi)
                        .addComponent(RdBttnNo))
                    .addComponent(TxtcantBanios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbBxTipContru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoConstruccion)
                    .addComponent(lblCarretera)
                    .addComponent(CmbBxTipoCarretera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropietario)
                    .addComponent(CmbBxPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado)
                    .addComponent(CmboBxEstadoViv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrecio)
                        .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDeposito))
                .addGap(26, 26, 26))
        );

        pnlViviendas.setBackground(new java.awt.Color(0, 153, 153));
        pnlViviendas.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        pnlViviendas.setForeground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoGuanaRent1.png"))); // NOI18N
        lblLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTituloViviendas.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloViviendas.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        lblTituloViviendas.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloViviendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloViviendas.setText("- Viviendas - ");

        javax.swing.GroupLayout pnlViviendasLayout = new javax.swing.GroupLayout(pnlViviendas);
        pnlViviendas.setLayout(pnlViviendasLayout);
        pnlViviendasLayout.setHorizontalGroup(
            pnlViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViviendasLayout.createSequentialGroup()
                .addGroup(pnlViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViviendasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)))
                    .addGroup(pnlViviendasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblLogo)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViviendasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTituloViviendas)
                .addGap(39, 39, 39))
        );
        pnlViviendasLayout.setVerticalGroup(
            pnlViviendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViviendasLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloViviendas)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clean.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pnlInformacionViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(250, 250, 250))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlInformacionViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(pnlViviendas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón GUARDAR — valida todos los campos, decide AGREGAR o MODIFICAR. Si
     * es Nueva → verifica que el ID no exista antes de guardar. Si es Edición →
     * permite cambiar datos y valida ID solo si cambió.
     *
     * @param evt Evento al presionar el botón Guardar
     */
    
    
    /**
     * valida,registra y modifica las propiedades de viviendas
     * @param evt al presionar el boton guardar
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        
        if (this.getTitle().equals("Editar Vivienda")) {
            Propietario duenioActual = viviendaEditar.getPropietario();
            for (int i = 1; i < CmbBxPropietarios.getItemCount(); i++) {
                Propietario p = listaPropietarios.getListaPropietarios().get(i - 1);
                if (p.equals(duenioActual)) {
                    CmbBxPropietarios.setSelectedIndex(i);
                    break;
                }
            }

            String estadoActual = viviendaEditar.getEstado();
            for (int i = 0; i < CmboBxEstadoViv.getItemCount(); i++) {
                if (CmboBxEstadoViv.getItemAt(i).toString().equals(estadoActual)) {
                    CmboBxEstadoViv.setSelectedIndex(i);
                    break;
                }
            }
        }

        if (txtIdVivienda.getText().isBlank()
                || TxtADescripcion.getText().isBlank()
                || TxtADireccion.getText().isBlank()
                || txtM2Contruc.getText().isBlank()
                || txtMtsLote.getText().isBlank()
                || CmbBxTipContru.getSelectedIndex() == 0
                || txtCantH.getText().isBlank()
                || TxtcantBanios.getText().isBlank()
                || CmbBxTipoCarretera.getSelectedIndex() == 0
                || txtPrecioBase.getText().isBlank()
                || txtDeposito.getText().isBlank()
                || CmbBxPropietarios.getSelectedIndex() == 0
                || CmboBxEstadoViv.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this,
                    "Hay campos vacíos, por favor complete todos los datos",
                    "Faltan datos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String idVivienda = txtIdVivienda.getText().trim();
            String descripcion = TxtADescripcion.getText().trim().replace(",", " -");
            String direccion = TxtADireccion.getText().trim().replace(",", " -");
            double mtsConstruc = Double.parseDouble(txtM2Contruc.getText().trim());
            double mtsLote = Double.parseDouble(txtMtsLote.getText().trim());
            String tipoConstruc = CmbBxTipContru.getSelectedItem().toString();
            boolean cochera = RdBttnSi.isSelected();
            int cantHabit = Integer.parseInt(txtCantH.getText().trim());
            double cantBanios = Double.parseDouble(TxtcantBanios.getText().trim());
            String carretera = CmbBxTipoCarretera.getSelectedItem().toString();
            double precioBase = Double.parseDouble(txtPrecioBase.getText().trim());
            double deposito = Double.parseDouble(txtDeposito.getText().trim());
            String estado = CmboBxEstadoViv.getSelectedItem().toString();
            int indiceProp = CmbBxPropietarios.getSelectedIndex();
            Propietario duenio = null;
            if (indiceProp > 0) {
                duenio = listaPropietarios.getListaPropietarios().get(indiceProp - 1);
            }

            if (duenio == null) {
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un Propietario.\nSi no hay ninguno, regístrelo primero.",
                        "Propietario requerido", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // AGREGAR NUEVA o EDITAR
            switch (this.getTitle()) {
                case "Agregar Nueva Vivienda" -> {
                    // MODO AGREGAR
                    Vivienda nueva = new Vivienda(idVivienda, descripcion, direccion,
                            mtsConstruc, mtsLote, tipoConstruc, cochera, cantHabit, cantBanios,
                            carretera, precioBase, deposito, duenio, estado);

                    if (listaViviendas.existeIdVivienda(idVivienda)) {
                        JOptionPane.showMessageDialog(this, "Ya existe una Vivienda con este ID: " + idVivienda,"ID Duplicado", JOptionPane.ERROR_MESSAGE);
                        txtIdVivienda.requestFocus();
                    } else {
                        listaViviendas.agregarVivienda(nueva);
                        listaViviendas.guardarArchivo();
                        JOptionPane.showMessageDialog(this, "Vivienda guardada con éxito:\n" + descripcion,"Guardado Exitoso", JOptionPane.INFORMATION_MESSAGE);
                        btnLimpiarActionPerformed(evt);
                        this.dispose();
                    }
                }

                case "Editar Vivienda" -> {
                    // MODO EDITAR -- id bloqueado
                    viviendaEditar.setDescripcion(descripcion);
                    viviendaEditar.setDireccion(direccion);
                    viviendaEditar.setMtsConstruct(mtsConstruc);
                    viviendaEditar.setMtsLote(mtsLote);
                    viviendaEditar.setTipoConstruccion(tipoConstruc);
                    viviendaEditar.setCochera(cochera);
                    viviendaEditar.setCantHabitac(cantHabit);
                    viviendaEditar.setCantBanios(cantBanios);
                    viviendaEditar.setCarretera(carretera);
                    viviendaEditar.setPrecioBase(precioBase);
                    viviendaEditar.setDepositoGarantia(deposito);
                    viviendaEditar.setPropietario(duenio);
                    viviendaEditar.setEstado(estado);

                    listaViviendas.guardarArchivo();
                    JOptionPane.showMessageDialog(this,"Datos de la Vivienda actualizados","Edición Exitosa", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Los campos de Metros, Habitaciones, Baños y Precio deben ser números",
                    "Dato numérico incorrecto", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * Borralos campos del formulario
     * @param evt al presionar el boton limpiar
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        
        txtIdVivienda.setText("");
        txtMtsLote.setText(null);
        TxtADescripcion.setText("");
        TxtADireccion.setText("");
        txtM2Contruc.setText("");
        txtCantH.setText(null);
        TxtcantBanios.setText(null);
        RdBttnSi.setSelected(false);
        RdBttnNo.setSelected(false);
        CmbBxTipContru.setSelectedIndex(0);
        CmbBxTipoCarretera.setSelectedIndex(0);
        CmbBxPropietarios.setSelectedIndex(0);
        CmboBxEstadoViv.setSelectedIndex(0);
        txtPrecioBase.setText("");
        txtDeposito.setText("");
        txtIdVivienda.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * Cancelar la inscripcion de la vivienda, advitiendo si tiene datos previos
     * @param evt 
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        boolean hayDatos = !txtIdVivienda.getText().trim().isEmpty()
                || txtMtsLote.getText() != null
                || TxtADescripcion.getText().trim().isEmpty() == false
                || TxtADireccion.getText().trim().isEmpty() == false
                || txtM2Contruc.getText() != null
                || CmbBxTipContru.getSelectedIndex() != 0
                || CmbBxPropietarios.getSelectedIndex() != 0;

        if (hayDatos) {
            int opcion = JOptionPane.showConfirmDialog(this,
                    "⚠️ Hay datos en el formulario que NO han sido guardados.\n\n"
                    + "¿Está SEGURO que desea SALIR?\n"
                    + "Se perderán todos los datos ingresados.",
                    "Confirmar Cancelación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (opcion != JOptionPane.YES_OPTION) {
                return; 
            }
        }
        this.dispose(); 
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Se ejecuta al abrir la ventana.
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (viviendaEditar != null) {
            txtIdVivienda.setText(viviendaEditar.getIdVivienda());
            txtIdVivienda.setEnabled(false); // ID no editable
            TxtADescripcion.setText(viviendaEditar.getDescripcion());
            TxtADireccion.setText(viviendaEditar.getDireccion());
            txtM2Contruc.setText(String.valueOf(viviendaEditar.getMtsConstruct()));
            txtMtsLote.setText(String.valueOf(viviendaEditar.getMtsLote()));
            CmbBxTipContru.setSelectedItem(viviendaEditar.getTipoConstruccion());
            RdBttnSi.setSelected(viviendaEditar.isCochera());
            RdBttnNo.setSelected(!viviendaEditar.isCochera());
            txtCantH.setText(String.valueOf(viviendaEditar.getCantHabitac()));
            TxtcantBanios.setText(String.valueOf(viviendaEditar.getCantBanios()));
            CmbBxTipoCarretera.setSelectedItem(viviendaEditar.getCarretera());
            txtPrecioBase.setText(String.valueOf(viviendaEditar.getPrecioBase()));
            txtDeposito.setText(String.valueOf(viviendaEditar.getDepositoGarantia()));
            CmboBxEstadoViv.setSelectedItem(viviendaEditar.getEstado());
            if (viviendaEditar.getPropietario() != null) {
                String nombreBuscar = viviendaEditar.getPropietario().getNomPropiet().trim();
                for (int i = 1; i < CmbBxPropietarios.getItemCount(); i++) {
                    String itemCombo = CmbBxPropietarios.getItemAt(i).toString().trim();
                    if (itemCombo.contains(nombreBuscar)) {
                        CmbBxPropietarios.setSelectedIndex(i);
                        break;
                    }
                }
            }
        }

    }//GEN-LAST:event_formWindowActivated

        private void cargarComboPropietarios() {
        CmbBxPropietarios.addItem("Seleccione un propietario");
        for (Propietario p : listaPropietarios.getListaPropietarios()) {
            CmbBxPropietarios.addItem(p.getNomPropiet() + " - " + p.getCedPropiet());
        }
    }

    private int leerEntero(String texto) {
        try {
            return (int) Double.parseDouble(texto.trim());
        } catch (Exception e) {
            return -1;
        }
    }

    private double leerDecimal(String texto) {
        try {
            return Double.parseDouble(texto.trim());
        } catch (Exception e) {
            return -1.0;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgNewVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgNewVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgNewVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgNewVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgNewVivienda dialog = new JDlgNewVivienda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbBxPropietarios;
    private javax.swing.JComboBox<String> CmbBxTipContru;
    private javax.swing.JComboBox<String> CmbBxTipoCarretera;
    private javax.swing.JComboBox<String> CmboBxEstadoViv;
    private javax.swing.JRadioButton RdBttnNo;
    private javax.swing.JRadioButton RdBttnSi;
    private javax.swing.JTextArea TxtADescripcion;
    private javax.swing.JTextArea TxtADireccion;
    private javax.swing.JTextField TxtcantBanios;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBanios;
    private javax.swing.JLabel lblCantHabt;
    private javax.swing.JLabel lblCarretera;
    private javax.swing.JLabel lblCochera;
    private javax.swing.JLabel lblDeposito;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdVivienda;
    private javax.swing.JLabel lblIlustrativo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblM2Construccion;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblTipoConstruccion;
    private javax.swing.JLabel lblTituloInfromacionVivienda;
    private javax.swing.JLabel lblTituloViviendas;
    private javax.swing.JPanel pnlInformacionViviendas;
    private javax.swing.JPanel pnlViviendas;
    private javax.swing.JTextField txtCantH;
    private javax.swing.JTextField txtDeposito;
    private javax.swing.JTextField txtIdVivienda;
    private javax.swing.JTextField txtM2Contruc;
    private javax.swing.JTextField txtMtsLote;
    private javax.swing.JTextField txtPrecioBase;
    // End of variables declaration//GEN-END:variables
}
