/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import datos.AlmacenamientoAlquileres;
import datos.AlmacenamientoInquilinos;
import datos.AlmacenamientoMensualidad;
import datos.AlmacenamientoPropietarios;
import datos.AlmacenamientoViviendas;
import java.awt.Image;
import java.awt.Toolkit;
import vista.DglAcercaDe;

/**
 *  ventana principal deL SISTEMA GUANARENT
 * @author cahb294
 */
public class JFrmSistemaAlquilerGuanaRent extends javax.swing.JFrame {

    public static AlmacenamientoPropietarios listaPropietarios;
    public static AlmacenamientoViviendas listaViviendas;
    public static AlmacenamientoInquilinos listaInquilinos;
    public static AlmacenamientoAlquileres listaAlquileres;
    
     /* Creates new form JFrmSistemaAlquilerGuanaRent
     */
    public JFrmSistemaAlquilerGuanaRent() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPropietarios = new javax.swing.JToggleButton();
        btnViviendas = new javax.swing.JToggleButton();
        btnInquilinos = new javax.swing.JToggleButton();
        btnAlquileres = new javax.swing.JToggleButton();
        btnMensualidad = new javax.swing.JToggleButton();
        btnGanancias = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lblTituloUsuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnItenGanancia = new javax.swing.JMenuItem();
        mnItemGanancia = new javax.swing.JMenuItem();
        mnacercade = new javax.swing.JMenu();
        mnitmInf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GuanaRent-CR");
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btnPropietarios.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Propietario8.png"))); // NOI18N
        btnPropietarios.setText("Propietarios");
        btnPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropietariosActionPerformed(evt);
            }
        });

        btnViviendas.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnViviendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vivienda8.png"))); // NOI18N
        btnViviendas.setText("Viviendas");
        btnViviendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViviendasActionPerformed(evt);
            }
        });

        btnInquilinos.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnInquilinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inqulino8.png"))); // NOI18N
        btnInquilinos.setText("Inquilinos");
        btnInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInquilinosActionPerformed(evt);
            }
        });

        btnAlquileres.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnAlquileres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alquileres8.png"))); // NOI18N
        btnAlquileres.setText("Alquileres");
        btnAlquileres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquileresActionPerformed(evt);
            }
        });

        btnMensualidad.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnMensualidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mensualidad8.png"))); // NOI18N
        btnMensualidad.setText("Mensualidad");
        btnMensualidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensualidadActionPerformed(evt);
            }
        });

        btnGanancias.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnGanancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ganancias.png"))); // NOI18N
        btnGanancias.setText("Ganancias");
        btnGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGananciasActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoGuanaRent1.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTituloUsuario.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        lblTituloUsuario.setForeground(new java.awt.Color(102, 102, 0));
        lblTituloUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloUsuario.setText("- Menu Principal - ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblTituloUsuario)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPropietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViviendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnInquilinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAlquileres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMensualidad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPropietarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViviendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInquilinos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlquileres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMensualidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGanancias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GuanaRent - Poster Publicitario.png"))); // NOI18N

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        mnItenGanancia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnItenGanancia.setText("Mensualidad");
        mnItenGanancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItenGananciaActionPerformed(evt);
            }
        });
        jMenu1.add(mnItenGanancia);

        mnItemGanancia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnItemGanancia.setText("Ganacias");
        mnItemGanancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemGananciaActionPerformed(evt);
            }
        });
        jMenu1.add(mnItemGanancia);

        jMenuBar1.add(jMenu1);

        mnacercade.setText("Acerca de");

        mnitmInf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnitmInf.setText("Informacion");
        mnitmInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmInfActionPerformed(evt);
            }
        });
        mnacercade.add(mnitmInf);

        jMenuBar1.add(mnacercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlquileresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquileresActionPerformed
        // TODO add your handling code here:
        //  Abre el formulario MAIN de Alquileres
    listaViviendas = new AlmacenamientoViviendas();
    listaInquilinos = new AlmacenamientoInquilinos();
    listaAlquileres = new AlmacenamientoAlquileres(); 
    listaViviendas.cargarArchivo();
    listaInquilinos.cargarArchivo();
    listaAlquileres.cargarArchivo();
    
    JDlgMainAlquiler ventana = new JDlgMainAlquiler(this, true,listaViviendas,listaInquilinos,listaAlquileres); 
    ventana.setLocationRelativeTo(null);
    ventana.setVisible(true);
    }//GEN-LAST:event_btnAlquileresActionPerformed

    private void btnPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropietariosActionPerformed
        // TODO add your handling code here:
        // Abre el formulario MAIN de Propietarios
        AlmacenamientoPropietarios lisPropietarios = new AlmacenamientoPropietarios();
        JDlgMainPropietario ventana = new JDlgMainPropietario(this, true,lisPropietarios);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnPropietariosActionPerformed

    private void btnViviendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViviendasActionPerformed
        // TODO add your handling code here:
        // Abre el formulario MAIN de Viviendas
        listaViviendas = new AlmacenamientoViviendas();
        listaPropietarios = new AlmacenamientoPropietarios();
        listaPropietarios.cargarArchivo(); 
        listaViviendas.cargarArchivo();
        JDlgMainVivienda ventana = new JDlgMainVivienda(this, true, listaViviendas, listaPropietarios);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

    }//GEN-LAST:event_btnViviendasActionPerformed

    private void btnInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInquilinosActionPerformed
        // TODO add your handling code here:
        // Abre el formulario MAIN de Inquilinos
        AlmacenamientoInquilinos lisInquilinos = new AlmacenamientoInquilinos();
        JDlgMainInquilino ventana = new JDlgMainInquilino(this, true,lisInquilinos);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnInquilinosActionPerformed

    private void btnMensualidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensualidadActionPerformed
        // TODO add your handling code here:
        //  Abre el formulario MAIN de Mensualidades
        AlmacenamientoMensualidad almacMensualidad = new AlmacenamientoMensualidad();
        AlmacenamientoAlquileres almacAlquileres = new AlmacenamientoAlquileres();

        almacMensualidad.cargarArchivo();  
        almacAlquileres.cargarArchivo();     
        JDlgMainMensualidad ventana = new JDlgMainMensualidad(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMensualidadActionPerformed

    private void btnGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGananciasActionPerformed
        // TODO add your handling code here:
       //  Abre el formulario de Ganancias / Reporte Financiero
        JDlgMainGanacias ventana = new JDlgMainGanacias(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGananciasActionPerformed

    private void mnItenGananciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItenGananciaActionPerformed
        // TODO add your handling code here:
        AlmacenamientoMensualidad almacMensualidad = new AlmacenamientoMensualidad();
        AlmacenamientoAlquileres almacAlquileres = new AlmacenamientoAlquileres();

        almacMensualidad.cargarArchivo();   
        almacAlquileres.cargarArchivo();   

        JDlgMainMensualidad ventana = new JDlgMainMensualidad(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_mnItenGananciaActionPerformed

    private void mnItemGananciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemGananciaActionPerformed
        // TODO add your handling code here:
        JDlgMainGanacias ventana = new JDlgMainGanacias(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_mnItemGananciaActionPerformed

    private void mnitmInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmInfActionPerformed
        // TODO add your handling code here:
        DglAcercaDe dlg = new DglAcercaDe(this, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_mnitmInfActionPerformed
       @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("img/Icono Alquiler de Vivienda.png"));

        return retValue;
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmSistemaAlquilerGuanaRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmSistemaAlquilerGuanaRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmSistemaAlquilerGuanaRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmSistemaAlquilerGuanaRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmSistemaAlquilerGuanaRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlquileres;
    private javax.swing.JToggleButton btnGanancias;
    private javax.swing.JToggleButton btnInquilinos;
    private javax.swing.JToggleButton btnMensualidad;
    private javax.swing.JToggleButton btnPropietarios;
    private javax.swing.JToggleButton btnViviendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblTituloUsuario;
    private javax.swing.JMenuItem mnItemGanancia;
    private javax.swing.JMenuItem mnItenGanancia;
    private javax.swing.JMenu mnacercade;
    private javax.swing.JMenuItem mnitmInf;
    // End of variables declaration//GEN-END:variables
}
